version : "3"
services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: exmple-database
      MARIADB_USER: MyWordPressUser
      MARIADB_PASSWORD: my_cool_secret

  # nginx:
  #   image: nginx
  #   ports:
  #     - "80:80"
  #   restart: always
  wordpress:
    image: wordpress
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: MyWordPressUser
      WORDPRESS_DB_PASSWORD: my_cool_secret
      WORDPRESS_DB_NAME: exmple-database
    ports :
      - "80:80"
#     volumes:
#        ["./wordpress:/var/www/html"]
# volumes:
#   mariadb: {}