version: "3"

services:
# ===================mariadb=====================
  mariadb:
    container_name: mariadb
    env_file:
      - .env
    build:
      context: ./requirements/mariaDB
      args:
        - MARIADB_DATABASE=${MARIADB_DATABASE}
        - MARIADB_PASSWORD=${MARIADB_PASSWORD}
        - MARIADB_USER=${MARIADB_USER}
        - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    restart: unless-stopped 
    image: mariadb
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

# =======================wordpress===============
  wordpress:
    container_name: wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    image: wordpress
    restart: always
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
  
# =====================nginx======================
  nginx:
    container_name: nginx_image
    env_file:
      - .env
    depends_on:
      - wordpress
    build: ./requirements/nginx
    image: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception


# ===============bonus==================
  web:
    container_name: web
    build: ./requirements/bonus/web
    image: web
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always
    expose:
        - "9000"

# ================redis=======================
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    image: redis
    networks:
      - inception
    restart: always
    expose:
        - "6379"

# ================adminer =======================
  adminer:
    # image: adminer:latest
    build: ./requirements/bonus/adminer
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 7777:8080
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
# ========network==========
networks:
  inception:
    driver: bridge

# ============volumes============
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/houaslam/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/houaslam/data/mariadb'
