version : "3"
services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_PASSWORD: my_cool_secret
      MARIADB_DATABASE: exmple-database
    # ports :
    #   - "3306:3306"
  nginx:
    image: nginx
    ports:
      - "8080:80"
    restart: always
  wordpress:
    image: wordpress
