version: "3"

services:
  # ===================mariadb=====================
  mariadb:
    container_name: mariadb
    env_file:
      - .env
    build:
      context: ./requirements/mariaDB
      args:
        - MARIADB_DATABASE=mariadb
        - MARIADB_PASSWORD=password
        - MARIADB_USER=mariadbuser
        - MARIADB_ROOT_PASSWORD=rootpassword
    restart: unless-stopped 
    image: mariadb
    expose:
      - "3306"
    volumes:
      - /var/lib/mysql
    networks:
      - inception

  # =======================wordpress===============
  wordpress:
    container_name: wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    image: wordpress
    restart: always
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
  
  # =====================nginx======================
  nginx:
    container_name: nginx
    env_file:
      - .env
    depends_on:
      - wordpress
    build: ./requirements/nginx
    image: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception

# ========network==========
networks:
  inception:
    driver: bridge

# ============volumes============
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/houaslam/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/houaslam/data/mariadb'

