version: "3"

services:
  # ===================mariadb=====================
  mariadb:
    container_name: mariadb
    build: ./requirements/mariaDB
    env_file:
      - .env
    restart: always
    expose:
      - "3306"
    volumes:
      - /home/debian/Desktop/Inception/maria:/var/bin/mysql
    networks:
      - inception

  # =======================wordpress===============
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    restart: always
    expose:
      - "9000"
    volumes:
      - /home/debian/Desktop/Inception/wordpress:/var/www/html
    networks:
      - inception
  
  # =====================nginx======================
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - /home/debian/Desktop/Inception/wordpress:/var/www/html
    networks:
      - inception

# ========network==========
networks:
  inception:
    driver: bridge

# ============volumes============
# volumes:
#   wordpress:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: '/home/debian/Desktop/Inception/wordpress'
#   mariadb:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: '/home/debian/Desktop/Inception/maria'

