version: "3" 
services:

#=====================nginx======================
  nginx :
    container_name: nginx
    depends_on:
      - wordpress
    # networks:
      # - inception
    build : ./requirements/nginx
    restart: always
    ports: 
      - "443:443"

#===================mariadb=====================
  mariadb:
    container_name: mariadb
    build: ./requirements/mariaDB
    env_file:
      - .env
    restart: always
    # networks:
      # - inception
    expose:
      - "3306"
    # volumes:
      - mariadb:/var/lib/mysql

#=======================wordpress===============
  wordpress:
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    # build: ./requirements/wordpress
    restart: always
    ports:
      - "8080:80"
    # networks:
      # - inception
    # volumes:
      # - wordpress:/var/www/wordpress
    # expose:
    #   - "9000"
# 