version: "3" 
services:

  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: MyR00tMARIADBPa$$5w0rD
      MARIADB_DATABASE: MyWordPressDatabaseName
      MARIADB_USER: MyWordPressUser
      MARIADB_PASSWORD: Pa$$5w0rD

  wordpress:
    depends_on:
      - mariadb
    image: wordpress
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: MyWordPressUser
      WORDPRESS_DB_PASSWORD: Pa$$5w0rD
      WORDPRESS_DB_NAME: MyWordPressDatabaseName