version: "3"

services:
# ===================mariadb=====================
  mariadb:
    container_name: mariadb
    env_file:
      - .env
    build: ./requirements/mariaDB
    restart: always 
    image: mariadb:inception
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

# =======================wordpress===============
  wordpress:
    container_name: wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    image: wordpress:inception
    restart: always
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
  
# =====================nginx======================
  nginx:
    container_name: nginx
    env_file:
      - .env
    depends_on:
      - wordpress
    build: ./requirements/nginx
    image: nginx:inception
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception


# ===============bonus==================
  web:
    container_name: web
    build: ./requirements/bonus/web
    image: web:inception
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always
    expose:
        - "9000"

# ================redis=======================
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    image: redis:inception
    networks:
      - inception
    restart: always
    ports:
        - "6379:6379"

# ================adminer =======================
  adminer:
    build: ./requirements/bonus/adminer
    image: adminer:inception
    container_name: adminer
    restart: always
    expose:
      - "7777"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception

# ========network==========
networks:
  inception:
    driver: bridge

# ============volumes============
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/houaslam/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/houaslam/data/mariadb'
