version: "3" 
services:

#===================mariadb=====================
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: ./requirements/mariaDB
    env_file:
      - .env
    restart: always
    expose:
      - "3306"

#=====================nginx======================
  nginx :
    container_name: nginx
    depends_on:
      - wordpress
    networks:
      - inception
    build : ./requirements/nginx
    restart: always
    ports: 
      - "443:443"

#=======================wordpress===============
  wordpress:
    container_name: wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    env_file:
      - .env
    build: ./requirements/wordpress
    restart: always
    expose:
      - "9000"
